server.port=8080
spring.application.name=inventory-manager

# Database - overridden by Vault in production
spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.thymeleaf.cache=false

# Actuator - exposed for Prometheus scraping
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

info.app.name=Inventory Manager
info.app.version=1.0.0
info.app.project=DevOps-Project-04
